apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spiffe-client
spec:
  secretName: spiffe-client-tls

  commonName: "spiffe-client"
  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - client auth

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
